# The title is the title of your Add-On
title: Metadata Grabber
# The description will be shown above the form when activating the Add-On
description: Takes metadata from a batch of documents and puts them in one csv file. 
# Type should always be object
type: object
# Properties are the fields for your form
properties: {}
 


