# The title is the title of your Add-On
title: Metadata Grabber
# The description will be shown above the form when activating the Add-On
description: Takes metadata from a batch of documents and puts them in one csv file. 
# Add instructions specific to the Add-On in the instructions field, optional
instructions: ''
# Type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the current search query
  - query
  # By the currently selected documents
  - selected
# Properties are the fields for your form
properties: {}
categories:
  - export


